export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const SET_AUTH_ERROR = "SET_AUTH_ERROR";

export const SET_AUTH_TOKENS = "SET_AUTH_TOKENS";

export const SET_LOADING = "SET_LOADING";

export const SUCCESS_REQUEST = "SUCCESS_REQUEST";

export const VALIDATION_ERROR = "VALIDATION_ERROR";

export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const SET_DETAIL_POST_REQUEST = "SET_DETAIL_POST_REQUEST";
export const SET_DETAIL_POST = "SET_DETAIL_POST";
export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";

export const SET_ALL_AUTHORS = "SET_ALL_AUTHORS";
export const CREATE_AUTHOR_REQUEST = "CREATE_AUTHOR_REQUEST";
export const SET_DETAIL_AUTHOR_REQUEST = "SET_DETAIL_AUTHOR_REQUEST";
export const SET_DETAIL_AUTHOR = "SET_DETAIL_AUTHOR";
export const EDIT_AUTHOR_REQUEST = "EDIT_AUTHOR_REQUEST";
export const DELETE_AUTHOR_REQUEST = "DELETE_AUTHOR_REQUEST";
export const SET_ALL_AUTHORS_TO_SELECT = "SET_ALL_AUTHORS_TO_SELECT";

export const SET_ALL_TAGS = "SET_ALL_TAGS";
export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const SET_DETAIL_TAG_REQUEST = "SET_DETAIL_TAG_REQUEST";
export const SET_DETAIL_TAG = "SET_DETAIL_TAG";
export const EDIT_TAG_REQUEST = "EDIT_TAG_REQUEST";
export const DELETE_TAG_REQUEST = "DELETE_TAG_REQUEST";
export const SET_ALL_TAGS_TO_SELECT = "SET_ALL_TAGS_TO_SELECT";

export const SET_PAGINATION = "SET_PAGINATION";

export const PAGE_CHANGE = "PAGE_CHANGE";
