export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const SET_AUTH_ERROR = "SET_AUTH_ERROR";

export const SET_AUTH_TOKENS = "SET_AUTH_TOKENS";

export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";

export const SET_ALL_AUTHORS = "SET_ALL_AUTHORS";
export const SET_ALL_AUTHORS_TO_SELECT = "SET_ALL_AUTHORS_TO_SELECT";

export const SET_ALL_TAGS = "SET_ALL_TAGS";
export const SET_ALL_TAGS_TO_SELECT = "SET_ALL_TAGS_TO_SELECT";

export const SET_PAGINATION = "SET_PAGINATION";

export const PAGE_CHANGE = "PAGE_CHANGE";
